name: Build and Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Убедитесь, что деплой будет происходить при пуше в основную ветку

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      # Шаг 1: Клонирование репозитория
      - name: Checkout
        uses: actions/checkout@v3

      # Шаг 2: Установка Python
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # Шаг 3: Установка зависимостей (MkDocs и необходимые плагины)
      - name: Install MkDocs and Dependencies
        run: |
          pip install mkdocs
          pip install mkdocs-material  # если используете тему Material

      # Шаг 4: Сборка сайта
      - name: Build site
        run: mkdocs build --strict

      # Шаг 5: Деплой на GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}  # Автоматический токен для доступа к репозиторию
          publish_dir: ./site  # Путь к папке с собранным сайтом (из MkDocs)

